#This config allows you to run a local debug version of timbuctoo
#it also explains the options that you need to configure a production-worthy version


#database files
databasePath: "/data/timbuctoo/database" #do not refer to a soft link
# JSON files
authorizationsPath: "/data/timbuctoo/data"
loginsFilePath: "/data/timbuctoo/data/logins.json"
usersFilePath: "/data/timbuctoo/data/users.json"

# Timeouts
# the 'duration' is a number
# the timeUnit is a 'java.util.concurrent.TimeUnit'
autoLogoutTimeout:
  duration: 8
  timeUnit: HOURS
searchResultAvailabilityTimeout:
  duration: 8
  timeUnit: HOURS
executeDatabaseInvariantCheckAt: -1


#Public timbuctoo url
baseUri: http://test.repository.huygens.knaw.nl # used to generate next and previous links of a search result

activeMq:
  #useShutdownHook=false is needed because the activeMq bundle already takes care of shutting down activeMq
  #using a vm:// url will also add two amq metrics to the dropwizard metrics. Using a remote url means you have
  #to export the metrics from the remote VM's jmx yourself. See http://activemq.apache.org/jmx.html for more info
  brokerUrl: vm://timbuctoo?broker.useShutdownHook=false

persistenceManager:
  useDummy: yes #set to "no" to connect to a real handle server
#  privateKeyFile:
#  cypher:
#  namingAuthority:
#  prefix:

federatedAuthentication:
  enabled: false

server:
  applicationConnectors:
    - type: http #Note! if you change this you might or might not also want to change the baseUri
      port: 9080 # should be equal with the port configured in timbuctoo.monit
  adminConnectors:
    - type: http
      port: 9081 # should be equal with the port configured in timbuctoo.monit
  requestLog:
    appenders: [] #All requests are already logged using logging.LoggingFilter so the seperate requestlog is not needed

logging:
  appenders:
    - type: file
      currentLogFilename: /data/timbuctoo/logs/timbuctoo.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /data/timbuctoo/logs/timbuctoo.log.%d
      archivedFileCount: 10
      timeZone: UTC
      logFormat: "- %d %-5p  %m [%c{60}] %marker %mdc %ex%n"

#enable this to send the logs to an external log server
    - type: gelf
      host: 146.20.68.219
      port: 12201
      useMarker: true #
      includeFullMDC: true #We put the request information in the MDC
  level: INFO

#enable this to send the metrics to graphite
#metrics:
#  reporters:
#     - type: graphite
#       host: 192.168.99.100
#       port: 32778
#       prefix: timbuctoo
