#This config allows you to run a local debug version of timbuctoo
#it also explains the options that you need to configure a production-worthy version


#database files
databasePath: "/root/timbuctoo-prod-db" #do not refer to a soft link
# JSON files
# This directory Timbuctoo reads and writes the authorizations a file for each vre.
authorizationsPath: "/data/auth/authorizations"
#These files contain 1 user with username="user" and password="password"
loginsFilePath: "/data/auth/logins.json"
usersFilePath: "/data/auth/users.json"

# Timeouts
# the 'duration' is a number
# the timeUnit is a 'java.util.concurrent.TimeUnit'
autoLogoutTimeout:
  duration: 8
  timeUnit: HOURS
searchResultAvailabilityTimeout:
  duration: 8
  timeUnit: HOURS
executeDatabaseInvariantCheckAt: -1

#Public timbuctoo url
baseUri: ${BASE_URI} # used to generate next and previous links of a search result
timbuctooSearchUrl: ${TIMBUCTOO_SEARCH_URL}
solrIndexTriggerEnabled: true
solrIndexingUrl: ${TIMBUCTOO_SEARCH_URL}


activeMq:
  #persistent=false means that the broker does not try to store the queue. This is not needed in a debugrun.
  #useShutdownHook=false is needed because the activeMq bundle already takes care of shutting down activeMq
  #using a vm:// url will also add two amq metrics to the dropwizard metrics. Using a remote url means you have
  #to export the metrics from the remote VM's jmx yourself. See http://activemq.apache.org/jmx.html for more info
  brokerUrl: vm://timbuctoo?broker.persistent=false&broker.useShutdownHook=false
  shutdownWaitInSeconds: 1 #use for debug runs only!

persistenceManager:
  useDummy: yes #set to "no" to connect to a real handle server
#  privateKeyFile:
#  cypher:
#  namingAuthority:
#  prefix:

federatedAuthentication:
  enabled: true
  authenticationServerUrl: DUMMY
  authenticationCredentials: DUMMY

#Note! disable this for production builds
allowGremlinEndpoint: true

server:
  applicationConnectors:
    - type: http #Note! if you change this you might or might not also want to change the baseUri
      port: 80 #Note! if you change this you might or might not also want to change the baseUri
  adminConnectors:
    - type: http
      port: 81
  requestLog:
    appenders: [] #All requests are already logged using logging.LoggingFilter so the seperate requestlog is not needed

logging:
  appenders:
    - type: console
      logFormat: "- %-5p  %m [%c{60}]%n"
#enable this to send the logs to an external log server
#    - type: gelf
#      host: 192.168.99.100
#      port: 32768
#      useMarker: true #
#      includeFullMDC: true #We put the request information in the MDC
  level: INFO

#enable this to send the metrics to graphite
#metrics:
#  reporters:
#     - type: graphite
#       host: 192.168.99.100
#       port: 32778
#       prefix: timbuctoo
