# JSON files
databasePath: "./src/spec/resources/database" #do not refer to a soft link
#contains one user with username=user and password=password
loginsFilePath: "./src/spec/resources/logins.json"
usersFilePath: "./src/spec/resources/users.json"

# Timeouts
# the 'duration' is a number
# the timeUnit is a 'java.util.concurrent.TimeUnit'
autoLogoutTimeout:
  duration: 8
  timeUnit: HOURS
searchResultAvailabilityTimeout:
  duration: 8
  timeUnit: HOURS
baseUri: http://example.com # used to generate next and previous links of a search result
