#use docker-compose up after a successful mvn package to run timbuctoo alongside the services that it would also use
#in production
timbuctoo:
  build: .
  ports:
    - 8080:80
    - 8081:8081
  volumes:
    - ./database:/root/database
    - ./logins.json:/root/resources/logins.json
    - ./users.json:/root/resources/users.json
  links:
    - graylog
    - graphite
  environment:
    DOCKER_COMPOSE_HOST: $DOCKER_HOST
    DOCKER_COMPOSE_PORT: 8080
    USE_DUMMY_HANDLE_SERVER: "yes"
graylog:
  image: graylog2/allinone
  ports:
    - 8082:443
    - 514/udp
    - 4001
    - 9000
    - 12201/udp
    - 12900
graphite:
  image: hopsoft/graphite-statsd
  ports:
    - 2003
    - 8083:80
grafana:
  image: grafana/grafana
  links:
    - graphite
  ports:
    - 8084:3000
#todo: add local handle server
