#config used while running acceptance tests
#refers to fixtures (database, json) needed for those tests

#database files
databasePath: "./src/spec/resources/database" #do not refer to a soft link
# JSON files
loginsFilePath: "./src/spec/resources/logins.json"
usersFilePath: "./src/spec/resources/users.json"

# Timeouts
# the 'duration' is a number
# the timeUnit is a 'java.util.concurrent.TimeUnit'
autoLogoutTimeout:
  duration: 8
  timeUnit: HOURS
searchResultAvailabilityTimeout:
  duration: 8
  timeUnit: HOURS

#Public timbuctoo url
baseUri: http://localhost:8080 # used to generate next and previous links of a search result

server:
  applicationConnectors:
    - type: http #Note! if you change this you might or might not also want to change the baseUri
      port: 8080 #Note! if you change this you might or might not also want to change the baseUri
      bindHost: 127.0.0.1 #Note! if you change this you might or might not also want to change the baseUri
  requestLog:
    appenders: [] #All requests are already logged using logging.LoggingFilter so the seperate requestlog is not needed

logging:
  appenders:
    - type: console
      logFormat: "- %-5p  %m [%c{30}]%n"
  level: "OFF"
